#!/usr/bin/python
# *-* coding: utf-8 *-*
# Author: Thomas Martin <thomas.martin.1@ulaval.ca>
# File: orb-header

## Copyright (c) 2010-2014 Thomas Martin <thomas.martin.1@ulaval.ca>
## 
## This file is part of ORB
##
## ORB is free software: you can redistribute it and/or modify it
## under the terms of the GNU General Public License as published by
## the Free Software Foundation, either version 3 of the License, or
## (at your option) any later version.
##
## ORB is distributed in the hope that it will be useful, but WITHOUT
## ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
## or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public
## License for more details.
##
## You should have received a copy of the GNU General Public License
## along with ORB.  If not, see <http://www.gnu.org/licenses/>.

#############################################
############ HEADER script ##################
#############################################

# This script helps the user to manipulate the header of a frame. 

import os, sys
import orb.core
from orb.core import Tools
import argparse
from argparse import ArgumentParser
import warnings


def main(args):
    
    warnings.filterwarnings(
                'ignore', message='Overwriting existing file.*',
                module='astropy.io.*')

    to = Tools(no_log=True)


    if os.path.isfile(args.fits_path):
        if not 'fits' in args.fits_path:
            with open(args.fits_path, 'r') as f:
                fits_list = [filename for filename in f]
                fits_list = to.sort_image_list(fits_list, 'spiomm')
        else:
            fits_list = [args.fits_path]
            
            
        for fits_path in fits_list:

            hdulist = to.read_fits(fits_path, return_hdu_only=True,
                                   fix_header=False)

            if args.hdu_index + 1 > len(hdulist):
                print ' > ERROR: given HDU index is too high, file only contains {} HDU'.format(len(hdulist))
                hdulist.info()
                sys.exit(2)

            hdu = hdulist[args.hdu_index]
            if args.subparser_name == 'print':
                print repr(hdu.header)
            elif args.subparser_name == 'key':
                if args.keyword in hdu.header:
                    print hdu.header[args.keyword]
                else:
                    print ' > ERROR: keyword {} does not exist.'.format(
                        args.keyword)
            elif args.subparser_name == 'del':
                if args.keyword in hdu.header:
                    del hdu.header[args.keyword]
                    hdulist.writeto(fits_path, clobber=True)
                else:
                    print ' > ERROR: keyword {} does not exist.'.format(
                        args.keyword)
            elif args.subparser_name == 'info':
                hdulist.info()
        
    else:
        print " > ERROR: File {} does not exist.".format(args.fits_path)
       
if __name__ == "__main__":

    parser = ArgumentParser(version=('ORB-version {}'.format(
                              orb.core.__version__)),
                            description=
                            "Manipulate the header of a FITS file.")


    parser.add_argument('-i', dest="hdu_index", default=0, type=int,
                        help="Change HDU index")

    subparsers = parser.add_subparsers(help='operation type', dest='subparser_name')

    parser_print = subparsers.add_parser('print', help='Print header content')

    parser_key = subparsers.add_parser('key', help='Print key value')

    parser_key.add_argument('keyword', help='Keyword to print')

    parser_del = subparsers.add_parser('del', help='Delete keyword (Warning: File will be overwritten)')
    
    parser_del.add_argument('keyword', help='Keyword to delete')

    parser_del = subparsers.add_parser('info', help='Print basic header info')

    parser.add_argument('fits_path', help='Path to the FITS file')

    if len(sys.argv) < 2:
        parser.print_usage()
        sys.exit(2)
        
    args=parser.parse_args()
    
    main(args)
