#!/usr/bin/python
# *-* coding: utf-8 *-*
# Author: Thomas Martin <thomas.martin.1@ulaval.ca>
# File: dstack

## Copyright (c) 2010-2014 Thomas Martin <thomas.martin.1@ulaval.ca>
## 
## This file is part of ORB
##
## ORB is free software: you can redistribute it and/or modify it
## under the terms of the GNU General Public License as published by
## the Free Software Foundation, either version 3 of the License, or
## (at your option) any later version.
##
## ORB is distributed in the hope that it will be useful, but WITHOUT
## ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
## or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public
## License for more details.
##
## You should have received a copy of the GNU General Public License
## along with ORB.  If not, see <http://www.gnu.org/licenses/>.

#############################################
############ DSTACK script ##################
#############################################

# This script helps the user to stack a set of frames in a cube. A
# list of frames path must be given. List files created by ORBS can be
# used. Custom lists can be created using the command:
# 'ls /path/to/file/*.fits > list'


import numpy as np

from orb.core import Tools

def usage(): 
    print """usage: orb-rollxz CUBE_NAME
    
    Roll axes of a cube in order to have frames along XZ. Y being the
    third axis"""
  
    sys.exit(2)

def main():

    if len(sys.argv) < 2: usage()

    cube_name = sys.argv[1]
    if os.path.exists(cube_name):
        data = Tools().read_fits(cube_name)
        data = np.rollaxis(data, 2, 1)
        Tools().write_fits(os.path.splitext(cube_name)[0] + '.xz.fits', data,
                           silent=True)
    else:
        print "File does not exist"
       
if __name__ == "__main__":
    main()
